### PR TITLE
[Fix bug] Negative distance when data has negative values

### PR DESCRIPTION
**Pull request by xwchen-07**

### CODE REVIEW

**Comment by wwwjk366** [comment]
I wouldn't do this. If negative values are not meant to be in the input then we should error catch that before feeding into the formulas

**Comment by xwchen-07** [comment]
> I wouldn't do this. If negative values are not meant to be in the input then we should error catch that before feeding into the formulas

**Comment by xwchen-07** [comment]
> I wouldn't do this. If negative values are not meant to be in the input then we should error catch that before feeding into the formulas

Negative values should be allowed to be in the input. The issue here is that when normalizing the distance between numerical variables, there is a small bug in the formula causing the final value to be negative. Here is how it is currently calculated in the code: abs((X_2 - X_1)/X_max) multiply by (X_max/(X_max - X_min)). We should also take the absolute value of the second term so that the output is also positive when X_max is a negative value.

**Comment by wwwjk366** [comment]
actually it makes sense now :)

**Pull request merged**
